### ISSUE TITLE
Jquery Issue

### ISSUE THREAD

**Issue by moumitahalder** [wcmarketplace/woocommerce-product-stock-alert#40]
Hello see the following errors from woocommerce-product-stock-alert

We see these with jQuery Migrate Helper plugin. Your code needs updating.

/wp-content/plugins/woocommerce-product-stock-alert/lib/jquery/qtip/qtip.js: jQuery.fn.delegate() is deprecated
/wp-content/plugins/woocommerce-product-stock-alert/assets/admin/js/admin.js: jQuery.fn.click() event shorthand is deprecated
/wp-content/plugins/woocommerce-product-stock-alert/assets/admin/js/admin.js: jQuery.fn.change() event shorthand is deprecated

**Comment by Ritwik460** [comment]
1.
From:-   .delegate()
To :-  .on()          //solution

2.
From:-.click(function)  .on(“click”, function)
To:-.on("click", function)       //solution
          or

From:-   .click()  
To:-   .trigger(“click”)      //solution

3.
From:-   .change(function() {
To:-  .on('change', function() {       //solution
